export type CidbFieldCode = {
  code: string;
  title: string;
};

export type CidbCategory = {
  code: string;
  title: string;
  fields: CidbFieldCode[];
};

export const OTHER_CATEGORY_CODE = "OTHER";

export const CIDB_CATEGORIES: CidbCategory[] = [
  {
    code: "CE",
    title: "Pembinaan Kejuruteraan Awam (CE)",
    fields: [
      { code: "CE01", title: "Pembinaan jalan dan pavemen" },
      { code: "CE02", title: "Pembinaan jambatan dan jeti" },
      { code: "CE03", title: "Struktur marin" },
      { code: "CE04", title: "Empangan" },
      { code: "CE05", title: "Terowong dan sokong bawah tanah" },
      { code: "CE06", title: "Struktur saliran, pengaliran dan kawalan banjir" },
      { code: "CE07", title: "Landasan rel" },
      { code: "CE08", title: "Sistem perlindungan dan penstabilan cerun" },
      { code: "CE09", title: "Saluran utama paip minyak atau gas" },
      { code: "CE10", title: "Kerja cerucuk" },
      { code: "CE11", title: "Kerja pembaikan struktur konkrit" },
      { code: "CE12", title: "Kerja penyiasatan tanah" },
      { code: "CE13", title: "Pemasangan papan iklan" },
      { code: "CE14", title: "Landskap di luar bangunan" },
      { code: "CE15", title: "Pelantar minyak dan gas" },
      { code: "CE16", title: "Kerja penyenggaraan struktur di bawah air" },
      { code: "CE17", title: "Lapangan terbang" },
      { code: "CE18", title: "Tebusguna tanah" },
      { code: "CE19", title: "Sistem pembentungan" },
      { code: "CE20", title: "Sistem bekalan air" },
      { code: "CE21", title: "Pembinaan kejuruteraan awam" },
      { code: "CE22", title: "Trek padang permainan sintetik" },
      { code: "CE23", title: "Kerja prestressing dan post tensioning" },
      { code: "CE24", title: "Struktur menara" },
      { code: "CE25", title: "Kerja meletup" },
      { code: "CE26", title: "Struktur berukir" },
      { code: "CE27", title: "Kerja penebatan haba / refractory" },
      { code: "CE28", title: "Acuan konkrit khusus" },
      { code: "CE29", title: "Pemasangan perancah" },
      { code: "CE30", title: "Kerja pensatabilan tanah" },
      { code: "CE31", title: "Struktur laluan kabel bawah tanah" },
      { code: "CE32", title: "Kerja penyenggaraan kejuruteraan awam" },
      { code: "CE33", title: "Telaga tiub" },
      { code: "CE34", title: "Kerja pemasangan konkrit pratuang" },
      { code: "CE35", title: "Ujian konkrit" },
      { code: "CE36", title: "Kerja tanah" },
      { code: "CE37", title: "Kerja serombong stesen kuasa" },
      { code: "CE38", title: "Penyenggaraan sistem pembetungan" },
      { code: "CE39", title: "Penyenggaraan sistem bekalan air" },
      { code: "CE40", title: "Kerja pengorekan dan kawalan hakisan" },
      { code: "CE41", title: "Kerja membina takungan air" },
      { code: "CE42", title: "Kerja mengecat jalan" },
      { code: "CE43", title: "Perabot jalan" },
    ],
  },
  {
    code: "B",
    title: "Pembinaan Bangunan (B)",
    fields: [
      { code: "B01", title: "IBS: Sistem konkrit pasang siap" },
      { code: "B02", title: "IBS: Sistem kerangka keluli" },
      { code: "B03", title: "Pemulihan dan pemuliharaan" },
      { code: "B04", title: "Kerja pembinaan bangunan" },
      { code: "B05", title: "Kerja cerucuk" },
      { code: "B06", title: "Kerja pembaikan struktur konkrit" },
      { code: "B07", title: "Hiasan dalaman" },
      { code: "B08", title: "Pemasangan bahan kalis air" },
      { code: "B09", title: "Landskap dalam bangunan" },
      { code: "B10", title: "Sistem paip air dalaman" },
      { code: "B11", title: "Pemasangan papan tanda pada bangunan" },
      { code: "B12", title: "Kerja pemasangan kaca" },
      { code: "B13", title: "Pemasangan jubin" },
      { code: "B14", title: "Kerja cat" },
      { code: "B15", title: "Pemasangan bumbung" },
      { code: "B16", title: "Kolam renang" },
      { code: "B17", title: "Kerja prestressing dan post tensioning" },
      { code: "B18", title: "Kerja logam" },
      { code: "B19", title: "IBS: Sistem formwork" },
      { code: "B20", title: "Sistem paip gas dalam bangunan" },
      { code: "B21", title: "Pemasangan perancah" },
      { code: "B22", title: "IBS: Sistem blok" },
      { code: "B23", title: "IBS: Sistem kerangka kayu" },
      { code: "B24", title: "Kerja penyenggaraan bangunan" },
      { code: "B25", title: "Penyambungan paip persendirian ke pembetung" },
      { code: "B26", title: "Kerja meroboh" },
      { code: "B27", title: "Perkhidmatan penyenggaraan sistem bekalan air atau pembetungan" },
      { code: "B28", title: "Kerja ubahsuai" },
      { code: "B29", title: "Kerja bangunan kesihatan" },
    ],
  },
  {
    code: "M",
    title: "Mekanikal (M)",
    fields: [
      { code: "M01", title: "Sistem hawa dingin dan pengedaran udara" },
      { code: "M02", title: "Sistem pencegahan dan perlindungan kebakaran" },
      { code: "M03", title: "Lift dan eskalator" },
      { code: "M04", title: "Sistem automasi bangunan" },
      { code: "M05", title: "Sistem untuk bengkel, kilang, kuari dan sebagainya" },
      { code: "M06", title: "Sistem peralatan perubatan" },
      { code: "M07", title: "Sistem peralatan dapur" },
      { code: "M08", title: "Sistem loji dandang dan tekanan berapi" },
      { code: "M09", title: "Sistem pemampatan dan penjanaan berasaskan mekanikal" },
      { code: "M10", title: "Sistem pendingin untuk kuasa penjanaan" },
      { code: "M11", title: "Pembinaan dan rawatan khusus" },
      { code: "M12", title: "Loji khusus" },
      { code: "M13", title: "Struktur pengerudian luar pantai" },
      { code: "M14", title: "Sistem kawalan pencemaran" },
      { code: "M15", title: "Kelengkapan mekanikal pelbagai" },
      { code: "M16", title: "Kren menara" },
      { code: "M17", title: "Sistem peralatan dobi" },
      { code: "M18", title: "Sistem air panas" },
      { code: "M19", title: "Pemasangan kelengkapan loji" },
      { code: "M20", title: "Penyenggaraan am mekanikal" },
      { code: "M21", title: "Kerja kimpalan" },
      { code: "M22", title: "Sistem pam" },
      { code: "M23", title: "Sistem SCADA dan telemetri" },
    ],
  },
  {
    code: "E",
    title: "Elektrik (E)",
    fields: [
      { code: "E01", title: "Sistem bunyi" },
      { code: "E02", title: "Sistem pengawasan dan keselamatan" },
      { code: "E03", title: "Sistem automasi bangunan" },
      { code: "E04", title: "Pemasangan voltan rendah" },
      { code: "E05", title: "Pemasangan voltan tinggi sehingga 11KV" },
      { code: "E06", title: "Sistem pencahayaan khas" },
      { code: "E07", title: "Sistem telekomunikasi dalaman" },
      { code: "E08", title: "Sistem telekomunikasi luaran" },
      { code: "E09", title: "Sistem pemasangan peralatan perubatan" },
      { code: "E10", title: "Sistem bekalan kuasa tanpa gangguan" },
      { code: "E11", title: "Kerja am elektrik" },
      { code: "E12", title: "Papan tanda elektrik" },
      { code: "E13", title: "Sistem telekomunikasi perkhidmatan rel" },
      { code: "E14", title: "Kabel rangkaian komputer" },
      { code: "E15", title: "Lampu landasan lapangan terbang" },
      { code: "E16", title: "Lampu jalan dan lampu isyarat" },
      { code: "E17", title: "Kabel bawah tanah voltan rendah" },
      { code: "E18", title: "Kabel bawah tanah voltan tinggi sehingga 11KV" },
      { code: "E19", title: "Kabel bawah tanah voltan tinggi melebihi 11KV sehingga 33KV" },
      { code: "E20", title: "Kabel bawah tanah voltan tinggi melebihi 33KV" },
      { code: "E21", title: "Talian atas voltan rendah" },
      { code: "E22", title: "Kabel talian atas voltan tinggi sehingga 33KV" },
      { code: "E23", title: "Kabel talian atas voltan tinggi melebihi 33KV" },
      { code: "E24", title: "Pemasangan voltan tinggi melebihi 11KV sehingga 33KV" },
      { code: "E25", title: "Pemasangan voltan tinggi melebihi 33KV" },
      { code: "E26", title: "Kerja mencantum kabel voltan rendah 1KV" },
      { code: "E27", title: "Kerja mencantum kabel sehingga 11KV" },
      { code: "E28", title: "Kerja mencantum kabel melebihi 11KV sehingga 33KV" },
      { code: "E29", title: "Kerja mencantum kabel 33KV sehingga 66KV" },
      { code: "E30", title: "Kerja mencantum kabel sehingga 132KV" },
      { code: "E31", title: "Kerja mencantum kabel tiada sekatan melebihi 132KV" },
      { code: "E32", title: "Janakuasa voltan rendah" },
      { code: "E33", title: "Janakuasa voltan tinggi sehingga 33KV" },
      { code: "E34", title: "Sistem solar fotovolta tersambung grid sehingga 72kW" },
      { code: "E35", title: "Sistem solar fotovolta tersambung grid melebihi 72kW" },
    ],
  },
  {
    code: "F",
    title: "Fasiliti (F)",
    fields: [
      { code: "F01", title: "Fasiliti bangunan dan infrastruktur" },
      { code: "F02", title: "Fasiliti bangunan penjagaan kesihatan" },
    ],
  },
  {
    code: OTHER_CATEGORY_CODE,
    title: "Lain-lain - sila nyatakan",
    fields: [],
  },
];

export function getCidbCategory(categoryCode: string) {
  return CIDB_CATEGORIES.find((category) => category.code === categoryCode);
}

export function getCidbField(categoryCode: string, fieldCode: string) {
  return getCidbCategory(categoryCode)?.fields.find((field) => field.code === fieldCode);
}
